//! Repro codegen.
//!
// A failing fuzzer input is a `.bin` and a trace diff, which still leaves the
// repro to be written by hand -- and the interesting ones are 40 operations
// deep into a trie built by 40 earlier ones.  `emit_repro` turns the input back
// into a standalone Rust program that uses only the public `pathmap` API, so a
// divergence can be pasted into `bin/zipper_bug_repros.rs`, shrunk by hand,
// or handed to someone who does not have the fuzzer.
//
// It decodes the *same bytes in the same order* as `run_ops`, including the
// operands that are decoded only to keep the stream aligned.  Any drift shows up
// immediately and loudly: a generated repro that no longer matches the input
// will not reproduce, so `--repro` output is worth compiling and running rather
// than trusting.

use crate::harness::*;

/// A byte slice as a Rust literal: `&[1u8, 2, 3]`, or `&[]` when empty.
pub fn rs_bytes(p: &[u8]) -> String {
    if p.is_empty() {
        "&[]".to_string()
    } else {
        let mut inner: Vec<String> = p.iter().map(|b| b.to_string()).collect();
        inner[0].push_str("u8");
        format!("&[{}]", inner.join(", "))
    }
}

/// The same, as an owned array expression rather than a reference, for call
/// sites like `ByteMask::from_iter(..)` where a leading `&` would bind to the
/// whole expression instead of the literal.  The empty case needs an explicit
/// element type; there is nothing to infer it from.
pub fn rs_mask(p: &[u8]) -> String {
    if p.is_empty() {
        "[0u8; 0]".to_string()
    } else {
        let mut inner: Vec<String> = p.iter().map(|b| b.to_string()).collect();
        inner[0].push_str("u8");
        format!("[{}]", inner.join(", "))
    }
}

/// Turn a fuzzer input into a standalone Rust program.
///
/// `upto` is the number of operations to emit; the divergent step from a trace
/// line `N <op> ...` is reproduced by `upto = N + 1`.
pub fn emit_repro(bytes: &[u8], upto: usize) -> String {
    let mut d = Dec { bytes, pos: 0 };
    let mut o = String::new();
    o.push_str(
        "//! Generated by `pathmap_trace --repro`.  Reproduces a fuzzer input as\n\
         //! plain `pathmap` API calls.\n\
         //!\n\
         //! `wz` writes into map0 and `rz` reads map1; they are separate maps so\n\
         //! both can be held at once.  Values are `u64`.\n\n\
         use pathmap::PathMap;\n\
         use pathmap::utils::ByteMask;\n\
         use pathmap::zipper::*;\n\n\
         fn main() {\n",
    );

    // ---- header: the same decode `decode_header` performs -----------------
    macro_rules! gh {
        ($e:expr) => {
            match $e {
                Some(x) => x,
                None => {
                    o.push_str("    // input ended inside the header\n}\n");
                    return o;
                }
            }
        };
    }
    o.push_str("    let mut map0 = PathMap::<u64>::new();\n");
    let n0 = gh!(d.modn(8));
    for _ in 0..n0 {
        let p = gh!(d.path(6));
        let v = gh!(d.u8()) as u64;
        o.push_str(&format!("    map0.set_val_at({}, {v});\n", rs_bytes(&p)));
    }
    o.push_str("    let mut map1 = PathMap::<u64>::new();\n");
    let n1 = gh!(d.modn(8));
    for _ in 0..n1 {
        let p = gh!(d.path(6));
        let v = gh!(d.u8()) as u64;
        o.push_str(&format!("    map1.set_val_at({}, {v});\n", rs_bytes(&p)));
    }
    let r0 = gh!(d.path(4));
    let r1 = gh!(d.path(4));
    // The harness creates both roots so a zipper cannot start off-trie.
    if !r0.is_empty() {
        o.push_str(&format!("    map0.create_path({});\n", rs_bytes(&r0)));
    }
    if !r1.is_empty() {
        o.push_str(&format!("    map1.create_path({});\n", rs_bytes(&r1)));
    }
    o.push_str(&format!(
        "\n    let mut wz = map0.write_zipper_at_path({});\n    let mut rz = map1.read_zipper_at_path({});\n\n",
        rs_bytes(&r0),
        rs_bytes(&r1)
    ));

    // ---- body -------------------------------------------------------------
    // In the body, exhausting the input simply ends the program -- as it does in
    // `run_ops` -- so this breaks out and still emits the tail.
    macro_rules! g {
        ($e:expr) => {
            match $e {
                Some(x) => x,
                None => break,
            }
        };
    }
    let mut step = 0usize;
    while step < upto {
        let op = match d.u8() {
            Some(b) => b as usize % NOPS,
            None => break,
        };
        // `z!` picks the zipper the target byte selects, exactly as `tgt!` does.
        macro_rules! z {
            ($t:expr) => {
                if $t == 0 { "wz" } else { "rz" }
            };
        }
        let line: String = match op {
            0 => { let t = g!(d.modn(2)); let p = g!(d.path(6));
                   format!("{}.descend_to({});", z!(t), rs_bytes(&p)) }
            1 => { let t = g!(d.modn(2)); let b = g!(d.path_byte());
                   format!("{}.descend_to_byte({b});", z!(t)) }
            2 => { let t = g!(d.modn(2)); let n = g!(d.modn(8));
                   format!("{}.ascend({n});", z!(t)) }
            3 => { let t = g!(d.modn(2)); format!("{}.ascend_byte();", z!(t)) }
            4 => { let t = g!(d.modn(2)); format!("{}.reset();", z!(t)) }
            5 => { let t = g!(d.modn(2)); format!("{}.descend_first_byte();", z!(t)) }
            6 => { let t = g!(d.modn(2)); format!("{}.descend_last_byte();", z!(t)) }
            7 => { let t = g!(d.modn(2)); let i = g!(d.modn(6));
                   format!("{}.descend_indexed_byte({i});", z!(t)) }
            8 => { let t = g!(d.modn(2)); format!("{}.descend_until();", z!(t)) }
            9 => { let t = g!(d.modn(2)); format!("{}.ascend_until();", z!(t)) }
            10 => { let t = g!(d.modn(2)); format!("{}.ascend_until_branch();", z!(t)) }
            11 => { let t = g!(d.modn(2)); format!("{}.to_next_sibling_byte();", z!(t)) }
            12 => { let t = g!(d.modn(2)); format!("{}.to_prev_sibling_byte();", z!(t)) }
            13 => { let t = g!(d.modn(2)); format!("{}.to_next_step();", z!(t)) }
            14 => { let _t = g!(d.modn(2)); "rz.to_next_val();".to_string() }
            15 => { let _t = g!(d.modn(2)); let k = g!(d.modn(4));
                    if k == 0 { "// descend_first_k_path(0): skipped by the harness".to_string() }
                    else { format!("rz.descend_first_k_path({k});") } }
            16 => { let _t = g!(d.modn(2)); let k = g!(d.modn(4));
                    if k == 0 { "// k_path_walk(0): skipped by the harness".to_string() }
                    else { format!(
                        "if rz.descend_first_k_path({k}) {{ let mut n = 1; while n < 32 && rz.to_next_k_path({k}) {{ n += 1; }} }}") } }
            17 => { let _t = g!(d.modn(2)); "rz.descend_last_path();".to_string() }
            18 => { let t = g!(d.modn(2)); let p = g!(d.path(6));
                    format!("{}.move_to_path({});", z!(t), rs_bytes(&p)) }
            19 => { let t = g!(d.modn(2)); let p = g!(d.path(6));
                    format!("{}.descend_to_existing({});", z!(t), rs_bytes(&p)) }
            20 => { let t = g!(d.modn(2)); let p = g!(d.path(6));
                    format!("{}.descend_to_val({});", z!(t), rs_bytes(&p)) }
            21 => { let t = g!(d.modn(2)); let b = g!(d.path_byte());
                    format!("{}.descend_to_existing_byte({b});", z!(t)) }
            22 => { let t = g!(d.modn(2)); let n = g!(d.modn(8));
                    format!("{}.descend_until_max_bytes({n});", z!(t)) }
            23 => { let t = g!(d.modn(2)); let p = g!(d.path(6));
                    format!("{}.descend_to_check({});", z!(t), rs_bytes(&p)) }
            24 => { let t = g!(d.modn(2)); let p = g!(d.path(6));
                    format!("{}.val_at({});", z!(t), rs_bytes(&p)) }
            25 => { let t = g!(d.modn(2));
                    if t == 0 { "wz.make_map().val_count();".to_string() }
                    else { "rz.make_map().val_count();".to_string() } }
            26 => { let t = g!(d.modn(2)); format!("{}.fork_read_zipper();", z!(t)) }
            27 => { let v = g!(d.u8()) as u64; format!("wz.set_val({v});") }
            28 => { let _pr = g!(d.boolean()); "wz.remove_val(false);".to_string() }
            29 => "wz.create_path();".to_string(),
            30 => "wz.prune_path();".to_string(),
            31 => "wz.prune_ascend();".to_string(),
            32 => { let _pr = g!(d.boolean()); "wz.remove_branches(false);".to_string() }
            33 => { let n = g!(d.modn(4)); let m = g!(d.path_n(n)); let _pr = g!(d.boolean());
                    format!("wz.remove_unmasked_branches(ByteMask::from_iter({}.iter().copied()), false);", rs_mask(&m)) }
            34 => "wz.graft(&rz);".to_string(),
            35 => { let p = g!(d.path(6));
                    format!("wz.graft_src_at(&rz, {});", rs_bytes(&p)) }
            36 => "wz.join_into(&rz);".to_string(),
            37 => "wz.join_map_into(rz.make_map());".to_string(),
            38 => { let _pr = g!(d.boolean()); "wz.meet_into(&rz, false);".to_string() }
            39 => { let _pr = g!(d.boolean()); "wz.subtract_into(&rz, false);".to_string() }
            40 => "wz.restrict(&rz);".to_string(),
            41 => "wz.restricting(&rz);".to_string(),
            42 => { let k = g!(d.modn(4)); let _pr = g!(d.boolean());
                    if k == 0 { "// join_k_path_into(0): skipped by the harness".to_string() }
                    else { format!("wz.join_k_path_into({k}, false);") } }
            43 => { let p = g!(d.path(6));
                    if p.is_empty() { "// insert_prefix(\"\"): skipped by the harness".to_string() }
                    else { format!("wz.insert_prefix({});", rs_bytes(&p)) } }
            44 => { let n = g!(d.modn(6)); format!("wz.remove_prefix({n});") }
            45 => { let _pr = g!(d.boolean());
                    "if let Some(m) = wz.take_map(false) { wz.graft_map(m); }".to_string() }
            46 => { let k = g!(d.modn(4)); let _pr = g!(d.boolean());
                    format!("if {k} != 0 && wz.child_count() != 0 {{ wz.meet_k_path_into({k}, false); }}") }
            47 => { let t = g!(d.modn(2));
                    format!("{{ let mut obs = Vec::new(); {}.descend_until_observed(&mut obs); }}", z!(t)) }
            48 => { let v = g!(d.u8()) as u64;
                    format!("if let Some(slot) = wz.get_val_mut() {{ *slot = {v}; }}") }
            49 => { let v = g!(d.u8()) as u64; format!("wz.get_val_or_set_mut({v});") }
            50 => { let v = g!(d.u8()) as u64; format!("wz.get_val_or_set_mut_with(|| {v});") }
            51 => { let t = g!(d.modn(2)); let p = g!(d.path(6));
                    format!("{{ {z}.val(); {z}.val_at({p}); }}", z = z!(t), p = rs_bytes(&p)) }
            52 => "rz.to_next_val();  // to_next_get_val".to_string(),
            53 => { let n = g!(d.modn(4)); let m = g!(d.path_n(n)); let ru = g!(d.boolean());
                    format!("wz.graft_masked_branches(&rz, ByteMask::from_iter({}.iter().copied()), {ru});", rs_mask(&m)) }
            54 => { let n = g!(d.modn(4)); let _m = g!(d.path_n(n)); let _ru = g!(d.boolean());
                    "// graft_child_maps: quarantined by the harness (FINDINGS #15)".to_string() }
            55 => { let p = g!(d.path(6));
                    format!("{{ let mut b = map1.read_zipper_at_path({}); b.descend_to({}); wz.meet_2(&rz, &b); }}",
                            rs_bytes(&r1), rs_bytes(&p)) }
            _ => "// nop".to_string(),
        };
        o.push_str(&format!("    /* {step:3} */ {line}\n"));
        step += 1;
    }

    o.push_str(
        "\n    drop(wz);\n\
         \n    // What the maps hold at the end -- compare against the trace's MAP0/MAP1.\n\
         \n    println!(\"MAP0 {:?}\", map0.iter().collect::<Vec<_>>());\n\
         \n    println!(\"MAP1 {:?}\", map1.iter().collect::<Vec<_>>());\n\
         }\n",
    );
    o
}
